feat(ft-update-trip-status): update trip status
atlp-rwanda/eagles-bn-backend pull request #30
Opened 2020-11-08 23:23 UTC by Patience250

#25 # What does this PR do?
updated trip status 
### Description of tasks to be completed
- change status from pending to rejected or approved
- protect routes for changing trip status
### How to test manually
- Clone the repository 
- Run npm install
- Run npm run dev command
- In postman send a put request  to ``localhost:4000/api/trips/:tripId'`` to update``trip status``

2020-11-12 08:00 UTC, niyodusengaclement requested changes
Fix these issues

2020-11-12 08:00 UTC, niyodusengaclement commented on src/middlewares/trip.js
> +    static validate(req, res, next) {
This validation should be done in validators! No need for middleware and validations that are working same thing

2020-11-12 08:00 UTC, niyodusengaclement commented on src/middlewares/trip.js
> +    static validateUpdate(req, res, next) {
This validation should be done in validators! No need for middleware and validations that are working the same thing

2020-11-12 08:00 UTC, niyodusengaclement commented on src/controllers/trip.js
> +            return res.status(403).json({ status: 403, message: "Trip not yours!" });
No need for repeating all of these response requirements as long as we have a response helper. Use onError or onSuccess to return response to the user

2020-11-12 08:00 UTC, niyodusengaclement commented on src/controllers/trip.js
> +        // if (req.user.role !== "manager") {
No comments

2020-11-12 20:31 UTC, niyodusengaclement approved these changes

2020-11-13 08:56 UTC, RedJanvier approved these changes

2020-11-14 18:47 UTC, merged