feat(signup): create user
atlp-rwanda/eagles-bn-backend pull request #9
Opened 2020-10-18 22:38 UTC by Patience250

- add user registration route
- add user registration contoller
- assign a jwt token to a user created

2020-10-19 08:04 UTC, niyodusengaclement requested changes

2020-10-19 08:04 UTC, niyodusengaclement commented on src/controllers/users.js
> +        res.status(400).send({ error: err })
Catch throws Internal server error not bad request. Learn about HTTP status code

2020-10-19 08:04 UTC, niyodusengaclement commented on src/routes/index.js
> +const router = express.Router()
Use ES6

2020-10-19 08:48 UTC, niyodusengaclement commented on src/utils/index.js
> +        iat: Date.now()
Add an email

2020-10-19 17:50 UTC, merged

2020-10-20 06:55 UTC, franko-bit approved these changes